import {
  User,
  Client,
  Property,
  Contract,
  Process,
  ProcessStage,
  Task,
  TaskChecklistItem,
  Maintenance,
  Inspection,
  ContractEvent,
  MoveOutFlow,
  WorkflowTemplate,
  NPSResponse,
  AccessProfile,
  ConciergeRecord,
} from '../types'

export const db = {
  accessProfiles: [
    {
      id: 'ap1',
      name: 'Corretor Padrão',
      permissions: {
        dashboard: { view: true, create: false, edit: false },
        properties: { view: true, create: false, edit: false },
        tasks: { view: true, create: true, edit: true },
        kanban: { view: true, create: true, edit: true },
        financial: { view: false, create: false, edit: false },
        contacts: { view: true, create: true, edit: true },
        concierge: { view: true, create: true, edit: true },
      },
    },
    {
      id: 'ap2',
      name: 'Assistente Financeiro',
      permissions: {
        dashboard: { view: true, create: false, edit: false },
        properties: { view: true, create: false, edit: false },
        tasks: { view: true, create: false, edit: false },
        kanban: { view: true, create: false, edit: false },
        financial: { view: true, create: true, edit: true },
        contacts: { view: true, create: false, edit: false },
        concierge: { view: true, create: true, edit: true },
      },
    },
  ] as AccessProfile[],

  users: [
    {
      id: 'u1',
      name: 'Carlos Silva',
      email: 'carlos@alugai.com.br',
      role: 'Administrador',
      profileLevel: 'Diretor',
      avatar: 'https://img.usecurling.com/ppl/thumbnail?seed=1',
      isActive: true,
    },
    {
      id: 'u2',
      name: 'Marina Costa',
      email: 'marina@alugai.com.br',
      role: 'Gestor',
      profileLevel: 'Gestor',
      avatar: 'https://img.usecurling.com/ppl/thumbnail?seed=2',
      isActive: true,
    },
    {
      id: 'u3',
      name: 'João Paulo',
      email: 'joao@alugai.com.br',
      role: 'Colaborador',
      profileLevel: 'Colaborador',
      accessProfileId: 'ap1',
      avatar: 'https://img.usecurling.com/ppl/thumbnail?seed=3',
      isActive: true,
    },
    {
      id: 'u4',
      name: 'Alice Santos',
      email: 'alice@alugai.com.br',
      role: 'Equipe de Vistoria',
      profileLevel: 'Colaborador',
      accessProfileId: 'ap1',
      avatar: 'https://img.usecurling.com/ppl/thumbnail?seed=4',
      isActive: true,
    },
    {
      id: 'u5',
      name: 'Ricardo Mendes',
      email: 'ricardo@alugai.com.br',
      role: 'Equipe Financeira',
      profileLevel: 'Colaborador',
      accessProfileId: 'ap2',
      avatar: 'https://img.usecurling.com/ppl/thumbnail?seed=5',
      isActive: true,
    },
    {
      id: 'u6',
      name: 'Camila Torres',
      email: 'camila@alugai.com.br',
      role: 'Concierge',
      profileLevel: 'Colaborador',
      accessProfileId: 'ap1',
      avatar: 'https://img.usecurling.com/ppl/thumbnail?seed=6',
      isActive: true,
    },
  ] as User[],

  clients: [
    {
      id: 'c1',
      name: 'Ana Beatriz Marques',
      email: 'ana.marques@email.com',
      phone: '(11) 98765-4321',
      whatsapp: '(11) 98765-4321',
      document: '123.456.789-00',
      rg: '12.345.678-9',
      birthDate: '1985-06-15',
      type: 'Inquilino',
      status: 'Ativo',
      healthScore: 95,
      lastContact: '18/10/2023',
      responsibleId: 'u6',
      npsClassification: 'Promotor',
      lastNpsScore: 10,
      lastNpsDate: '20/10/2023',
      aiRiskDetection: false,
    },
    {
      id: 'c2',
      name: 'Roberto Almeida',
      email: 'roberto@email.com',
      phone: '(11) 91234-5678',
      whatsapp: '(11) 91234-5678',
      document: '098.765.432-11',
      type: 'Proprietário',
      status: 'Em Risco',
      healthScore: 40,
      responsibleId: 'u2',
      npsClassification: 'Detrator',
      lastNpsScore: 4,
      lastNpsDate: '10/04/2024',
      npsLowReasons: ['Demora excessiva na resposta de manutenção'],
      riskReasons: ['NPS Detrator recente', 'Risco de Churn (Quebra de contrato)'],
      aiRiskDetection: true,
    },
    {
      id: 'c3',
      name: 'Fernanda Costa',
      email: 'fernanda@email.com',
      phone: '(11) 99876-5432',
      whatsapp: '(11) 99876-5432',
      document: '234.567.890-12',
      type: 'Inquilino',
      status: 'Ativo',
      healthScore: 88,
      responsibleId: 'u6',
      npsClassification: 'Neutro',
      lastNpsScore: 8,
      lastNpsDate: '15/11/2023',
      aiRiskDetection: false,
    },
    {
      id: 'c4',
      name: 'Julio Santos',
      email: 'julio@email.com',
      phone: '(11) 94567-8901',
      whatsapp: '(11) 94567-8901',
      document: '345.678.901-23',
      type: 'Proprietário',
      status: 'Inativo',
      healthScore: 0,
      npsClassification: 'Sem Avaliação',
    },
  ] as Client[],

  properties: [
    {
      id: 'p1',
      ownerId: 'c2',
      title: 'Ap 102 - Bela Vista',
      address: 'Rua das Flores',
      number: '123',
      neighborhood: 'Bela Vista',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01311-000',
      type: 'Apartamento',
      status: 'Alugado',
      price: 4500,
      image: 'https://img.usecurling.com/p/400/300?q=apartment',
    },
    {
      id: 'p2',
      ownerId: 'c4',
      title: 'Casa 4 - Pinheiros',
      address: 'Av. Paulista',
      number: '1000',
      neighborhood: 'Pinheiros',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01310-100',
      type: 'Casa',
      status: 'Em Desocupação',
      price: 7200,
      image: 'https://img.usecurling.com/p/400/300?q=house',
    },
    {
      id: 'p3',
      ownerId: 'c2',
      title: 'Sala Comercial - Centro',
      address: 'Rua Augusta',
      number: '500',
      neighborhood: 'Consolação',
      city: 'São Paulo',
      state: 'SP',
      type: 'Comercial',
      status: 'Alugado',
      price: 2800,
      image: 'https://img.usecurling.com/p/400/300?q=office',
    },
  ] as Property[],

  contracts: [
    {
      id: 'CTR-001',
      tenantId: 'c1',
      ownerId: 'c2',
      propertyId: 'p1',
      startDate: '12/10/2023',
      endDate: '12/10/2025',
      rentValue: 4500,
      rentDueDate: 5,
      keyDeliveryDate: '15/10/2023',
      status: 'Ativo',
      healthScore: 95,
      guaranteeType: 'Seguro Fiança',
      guaranteeValue: 600,
      generalResponsibleId: 'u2',
      conciergeResponsibleId: 'u6',
    },
    {
      id: 'CTR-002',
      tenantId: 'c3',
      ownerId: 'c4',
      propertyId: 'p2',
      startDate: '15/11/2022',
      endDate: '15/11/2024',
      rentValue: 7200,
      rentDueDate: 10,
      keyDeliveryDate: '20/11/2022',
      status: 'Em Desocupação',
      healthScore: 40,
      guaranteeType: 'Caução',
      guaranteeValue: 21600,
      generalResponsibleId: 'u1',
    },
    {
      id: 'CTR-003',
      tenantId: 'c1',
      ownerId: 'c4',
      propertyId: 'p3',
      startDate: new Date().toLocaleDateString('pt-BR'),
      endDate: '10/10/2026',
      rentValue: 5500,
      status: 'Ativo',
      healthScore: 100,
      guaranteeType: 'Fiador',
    },
    {
      id: 'CTR-004',
      tenantId: 'c3',
      ownerId: 'c2',
      propertyId: 'p1',
      startDate: new Date().toLocaleDateString('pt-BR'),
      endDate: '10/10/2026',
      rentValue: 3000,
      status: 'Ativo',
      healthScore: 90,
      guaranteeType: 'Caução',
    },
  ] as Contract[],

  conciergeRecords: [
    {
      id: 'conc_1',
      cliente_nome: 'Ana Beatriz Marques',
      proprietario_nome: 'Roberto Almeida',
      imovel: 'Ap 102 - Bela Vista',
      contrato_id: 'CTR-001',
      data_entrega_chave: '15/10/2023',
      data_inicio_contrato: '12/10/2023',
      data_fim_contrato: '12/10/2025',
      data_vencimento_boleto: '05/11/2023',
      etapa_atual: 'ESTABILIZACAO',
      responsavel_atual: 'u4',
      ultimo_contato: '25/10/2023',
      proximo_contato: '25/11/2023',
      status_cliente: 'ativo',
    },
    {
      id: 'conc_2',
      cliente_nome: 'Fernanda Costa',
      proprietario_nome: 'Julio Santos',
      imovel: 'Casa 4 - Pinheiros',
      contrato_id: 'CTR-002',
      data_entrega_chave: '20/11/2022',
      data_inicio_contrato: '15/11/2022',
      data_fim_contrato: '15/11/2024',
      data_vencimento_boleto: '10/12/2022',
      etapa_atual: 'PRE_RENOVACAO',
      responsavel_atual: 'u6',
      ultimo_contato: '10/08/2024',
      proximo_contato: '15/09/2024',
      status_cliente: 'renovacao',
    },
  ] as ConciergeRecord[],

  processes: [
    {
      id: 'proc1',
      name: 'Jornada do Contrato Padrão',
      description: 'Fluxo padrão de ciclo de vida do contrato',
    },
  ] as Process[],

  stages: [
    { id: 'stg_entrada', processId: 'proc1', name: 'Vistoria Entrada', order: 1 },
    { id: 'stg_assinaturas', processId: 'proc1', name: 'Assinatura Contrato', order: 2 },
    { id: 'stg_chaves', processId: 'proc1', name: 'Entrega Chave', order: 3 },
    { id: 'stg_pos_mudanca', processId: 'proc1', name: 'Pós Mudança', order: 4 },
    { id: 'stg_pagamento', processId: 'proc1', name: 'Pagamento Proprietário', order: 5 },
    { id: 'stg_preventiva', processId: 'proc1', name: 'Vistoria Preventiva', order: 6 },
    { id: 'stg_renovacao', processId: 'proc1', name: 'Renovação Contrato', order: 7 },
  ] as ProcessStage[],

  tasks: [
    {
      id: 't1',
      title: 'Conferência de Assinaturas - CTR-001',
      stageId: 'stg_assinaturas',
      propertyId: 'p1',
      contractId: 'CTR-001',
      assigneeIds: ['u1', 'u3'],
      type: 'Operacional',
      deadline: `${new Date(Date.now() - 86400000 * 2).toLocaleDateString('pt-BR')} 10:00`, // Overdue
      sla: 24,
      status: 'Atrasada',
      priority: 'Crítica',
      notes: 'Assinaturas validadas pendentes.',
      attachments: [
        { id: 'a1', name: 'Contrato_Assinado.pdf', url: '#' },
        {
          id: 'a2',
          name: 'evidencia_problema.jpg',
          url: 'https://img.usecurling.com/p/400/400?q=leak',
        },
      ],
      delayStatus: 'delayed',
      autoGenerated: true,
      specialStatus: 'Crítica',
      aiUrgency: 'Alta',
      aiRiskFlag: false,
      comments: [
        {
          id: 'c1',
          author: 'Marina Costa',
          date: '12/10/2023 16:00',
          text: 'Pessoal, precisamos finalizar isso ainda hoje. O proprietário está aguardando.',
        },
      ],
      history: [
        {
          id: 'h1',
          date: '11/10/2023 09:00',
          user: 'Sistema',
          action: 'Tarefa gerada automaticamente.',
        },
        {
          id: 'h2',
          date: '12/10/2023 15:30',
          user: 'João Paulo',
          action: 'Faltando assinatura do fiador.',
        },
      ],
    },
    {
      id: 't2',
      title: 'Vistoria de Entrada - CTR-001',
      stageId: 'stg_entrada',
      propertyId: 'p1',
      contractId: 'CTR-001',
      assigneeIds: ['u1', 'u4'],
      type: 'Operacional',
      deadline: `${new Date(Date.now() + 86400000 * 3).toLocaleDateString('pt-BR')} 14:30`, // Future
      sla: 48,
      status: 'Em Andamento',
      priority: 'Média',
      notes: 'Agendada para as 14h com o inquilino.',
      attachments: [],
      delayStatus: 'on-time',
      autoGenerated: true,
      specialStatus: 'Em acompanhamento',
      aiUrgency: 'Normal',
      comments: [],
      history: [
        { id: 'h3', date: '14/10/2023 10:00', user: 'Alice Santos', action: 'Vistoria agendada.' },
      ],
    },
    {
      id: 't8',
      title: 'Contato Urgente (Recuperação NPS)',
      stageId: 'stg_pos_mudanca',
      propertyId: 'p1',
      contractId: 'CTR-001',
      assigneeIds: ['u2'],
      type: 'Concierge',
      deadline: `${new Date().toLocaleDateString('pt-BR')} 18:00`,
      sla: 12,
      status: 'Pendente',
      priority: 'Alta',
      notes:
        'Cliente Roberto (Proprietário) classificado como Detrator (Nota 4). Entrar em contato para entender o problema com a demora de manutenção.',
      attachments: [],
      delayStatus: 'critical',
      autoGenerated: true,
      specialStatus: 'Crítica',
      aiUrgency: 'Crítica',
      aiRiskFlag: true,
      comments: [],
    },
  ] as Task[],

  checklists: [
    {
      id: 'cl1',
      taskId: 't1',
      description: 'Validar DocuSign Fiador',
      isCompleted: false,
      isMandatory: true,
    },
    {
      id: 'cl1_b',
      taskId: 't1',
      description: 'Validar DocuSign Locatário',
      isCompleted: true,
      isMandatory: true,
    },
  ] as TaskChecklistItem[],

  maintenances: [
    {
      id: 'm1',
      propertyId: 'p1',
      contractId: 'CTR-001',
      requesterId: 'c1',
      description: 'Vazamento na pia do banheiro',
      status: 'Em Execução',
      reportedDate: '10/02/2024',
      scheduledDate: '12/02/2024',
      cost: 150,
      payer: 'Proprietário',
      assignedProfessional: 'Encanador Silva ME',
    },
  ] as Maintenance[],

  inspections: [
    {
      id: 'i1',
      propertyId: 'p1',
      contractId: 'CTR-001',
      inspectorId: 'u4',
      type: 'Entrada',
      date: '15/10/2023',
      status: 'Concluída',
      reportUrl: 'link',
      maintenanceRequired: false,
      entryPhotoUrl: 'https://img.usecurling.com/p/400/300?q=clean%20room',
    },
  ] as Inspection[],

  contractEvents: [
    {
      id: 'ce1',
      contractId: 'CTR-001',
      date: '12 Out 2023',
      title: 'Contrato Assinado',
      type: 'contract',
      description: 'Contrato de locação firmado por 30 meses.',
    },
    {
      id: 'ce6',
      contractId: 'CTR-001',
      date: '20 Out 2023',
      title: 'NPS Respondido (Inquilino)',
      type: 'nps',
      description: 'Ana Beatriz avaliou a imobiliária com Nota 10 (Promotor).',
    },
    {
      id: 'ce7',
      contractId: 'CTR-001',
      date: '20 Out 2023',
      title: 'Link Google Review Enviado',
      type: 'system',
      description:
        'Automação NPS: Cliente classificado como Promotor. Link de avaliação no Google enviado.',
    },
  ] as ContractEvent[],

  moveOutFlows: [
    {
      id: 'mo1',
      contractId: 'CTR-002',
      noticeDate: '01/10/2024',
      expectedExitDate: '30/10/2024',
      stage: 'vistoria',
    },
  ] as MoveOutFlow[],

  npsResponses: [
    {
      id: 'nps1',
      clientId: 'c1',
      contractId: 'CTR-001',
      score: 10,
      classification: 'Promotor',
      date: '20/10/2023',
      comment: 'Excelente atendimento desde a assinatura do contrato!',
      sourceTrigger: '7_days_move_in',
      googleReviewSent: true,
    },
    {
      id: 'nps2',
      clientId: 'c2',
      score: 4,
      classification: 'Detrator',
      date: '10/04/2024',
      comment: 'Demora excessiva para resolver problema de encanamento.',
      sourceTrigger: 'maintenance_resolved',
      googleReviewSent: false,
    },
    {
      id: 'nps3',
      clientId: 'c3',
      contractId: 'CTR-002',
      score: 8,
      classification: 'Neutro',
      date: '15/11/2023',
      comment: 'Tudo ok, mas a vistoria atrasou um pouco no dia.',
      sourceTrigger: '6_months_contract',
      googleReviewSent: false,
    },
    {
      id: 'nps4',
      clientId: 'mock5',
      score: 9,
      classification: 'Promotor',
      date: '01/01/2024',
      sourceTrigger: 'renewal_30_days',
      googleReviewSent: true,
    },
    {
      id: 'nps5',
      clientId: 'mock6',
      score: 10,
      classification: 'Promotor',
      date: '02/02/2024',
      sourceTrigger: 'property_leased',
      googleReviewSent: true,
    },
    {
      id: 'nps6',
      clientId: 'mock7',
      score: 5,
      classification: 'Detrator',
      date: '03/03/2024',
      sourceTrigger: 'maintenance_resolved',
      googleReviewSent: false,
    },
    {
      id: 'nps7',
      clientId: 'mock8',
      score: 7,
      classification: 'Neutro',
      date: '04/04/2024',
      sourceTrigger: '6_months_contract',
      googleReviewSent: false,
    },
    {
      id: 'nps8',
      clientId: 'mock9',
      score: 9,
      classification: 'Promotor',
      date: '05/05/2024',
      sourceTrigger: 'recovery_resend',
      googleReviewSent: true,
    },
  ] as NPSResponse[],
}

export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: 'wf1',
    name: 'Jornada Padrão de Locação',
    type: 'Fluxo de Locação',
    version: 'v2.1',
    isActive: true,
    stages: [
      {
        id: 'stg1',
        name: 'Vistoria de Entrada',
        tasks: [
          { id: 't1', name: 'Agendar Vistoria', sla: 24, isMandatory: true, hasChecklist: false },
          { id: 't2', name: 'Realizar Vistoria', sla: 48, isMandatory: true, hasChecklist: true },
        ],
      },
    ],
  },
]

export const aiConfigData = {
  budgetBrl: 150,
  tokensUsed: 1280000,
  manualBlock: false,
}

export const automationsData = [
  {
    id: 1,
    name: 'Jornada Padrão - Novo Contrato',
    condition: 'Contrato Criado',
    action: 'Criar tarefas: Vistoria Entrada, Assinatura',
    active: true,
  },
  {
    id: 12,
    name: 'Concierge - Check-in Pós-Mudança',
    condition: '7 dias após Entrega de Chaves',
    action: 'Criar Tarefa de Acolhimento (Check-in)',
    active: true,
  },
  {
    id: 13,
    name: 'Alerta SLA - Risco Operacional',
    condition: 'Tempo de resposta excedido em 20%',
    action: 'Escalonar para Gestor e Tag de Urgência IA',
    active: true,
  },
  {
    id: 14,
    name: 'Blindagem de Cliente (Inatividade)',
    condition: 'Ticket aberto > 48h sem atualização',
    action: 'Lembrete: Atualizar cliente (mesmo sem solução)',
    active: true,
  },
  {
    id: 15,
    name: 'Janela de Renovação Proativa',
    condition: 'Contrato a 90 dias do vencimento',
    action: 'Iniciar fluxo de sondagem de renovação',
    active: true,
  },
  {
    id: 8,
    name: 'NPS - Disparo Inquilino (Pós-Mudança)',
    condition: 'Data atual = Entrega de Chaves + 7 dias',
    action: 'Enviar Pesquisa NPS por WhatsApp/Email',
    active: true,
  },
  {
    id: 10,
    name: 'NPS - Workflow Detrator',
    condition: 'Classificação NPS = Detrator',
    action: 'Reduzir Health Score + Criar Tarefa "Contato Urgente"',
    active: true,
  },
]

export const teamProductivityData = db.users
  .filter((u) => u.role !== 'Administrador')
  .map((user) => {
    const userTasks = db.tasks.filter((t) => t.assigneeIds.includes(user.id))
    return {
      name: user.name.split(' ')[0],
      completed: userTasks.filter((t) => t.status === 'Concluída').length,
      pending: userTasks.filter((t) => t.status !== 'Concluída').length,
    }
  })

export const portfolioGrowthData = [
  { month: 'Jul', novos: 45, rescisoes: 12, saldo: 33 },
  { month: 'Ago', novos: 52, rescisoes: 15, saldo: 37 },
  { month: 'Set', novos: 48, rescisoes: 10, saldo: 38 },
  { month: 'Out', float: 61, rescisoes: 18, saldo: 43 },
  { month: 'Nov', novos: 59, rescisoes: 14, saldo: 45 },
  { month: 'Dez', float: 75, rescisoes: 11, saldo: 64 },
]

export const operationalHealthData = [
  {
    name: 'Concluídas',
    value: db.tasks.filter((t) => t.status === 'Concluída').length,
    fill: 'hsl(var(--success))',
  },
  {
    name: 'Em Andamento',
    value: db.tasks.filter((t) => t.status === 'Em Andamento').length,
    fill: 'hsl(var(--primary))',
  },
  {
    name: 'Atrasadas',
    value: db.tasks.filter((t) => t.status === 'Atrasada').length,
    fill: 'hsl(var(--destructive))',
  },
]

export const alertsData = [
  {
    id: 'a1',
    type: 'danger',
    title: 'SLA Crítico: Vistoria de Entrada (Ap 102)',
  },
  {
    id: 'a2',
    type: 'warning',
    title: 'Risco de Churn: Cliente Detrator sem follow-up',
  },
  {
    id: 'a3',
    type: 'info',
    title: '2 contratos a menos de 30 dias do vencimento',
  },
]
