export type UserRole =
  | 'Administrador'
  | 'Gestor'
  | 'Colaborador'
  | 'Equipe de Vistoria'
  | 'Equipe Administrativa'
  | 'Equipe Financeira'
  | 'Equipe Comercial'
  | 'Concierge'

export type UserProfileLevel = 'Colaborador' | 'Gestor' | 'Diretor'

export type AppModule =
  | 'dashboard'
  | 'properties'
  | 'tasks'
  | 'kanban'
  | 'financial'
  | 'contacts'
  | 'concierge'

export interface ModulePermissions {
  view: boolean
  create: boolean
  edit: boolean
}

export interface AccessProfile {
  id: string
  name: string
  permissions: Record<AppModule, ModulePermissions>
}

export type ClientType = 'Inquilino' | 'Proprietário' | 'Ambos'

export interface User {
  id: string
  name: string
  email: string
  role: UserRole
  profileLevel?: UserProfileLevel
  accessProfileId?: string
  avatar: string
  isActive?: boolean
}

export interface Client {
  id: string
  name: string
  email: string
  phone: string
  whatsapp: string
  document: string // CPF or CNPJ
  rg?: string
  birthDate?: string
  type: ClientType
  status: 'Ativo' | 'Inativo' | 'Em Risco'
  healthScore: number
  lastContact?: string
  responsibleId?: string
  npsClassification?: 'Promotor' | 'Neutro' | 'Detrator' | 'Sem Avaliação'
  lastNpsScore?: number
  lastNpsDate?: string
  riskReasons?: string[]
  npsLowReasons?: string[]
  aiRiskDetection?: boolean
  inRedForDays?: number
}

export interface Property {
  id: string
  ownerId: string
  title: string
  address: string
  number?: string
  neighborhood: string
  city: string
  state?: string
  zipCode?: string
  type: 'Apartamento' | 'Casa' | 'Comercial' | 'Terreno'
  status: 'Disponível' | 'Alugado' | 'Em Manutenção' | 'Em Desocupação'
  price: number
  image: string
}

export interface Contract {
  id: string
  tenantId: string
  ownerId: string
  propertyId: string
  startDate: string
  endDate: string
  rentValue: number
  rentDueDate?: number
  keyDeliveryDate?: string
  status: 'Ativo' | 'Encerrado' | 'Renovação Pendente' | 'Rescindido' | 'Em Desocupação'
  healthScore: number
  guaranteeType?: 'Seguro Fiança' | 'Caução' | 'Fiador' | 'Título de Capitalização' | 'Sem Garantia'
  guaranteeValue?: number
  generalResponsibleId?: string
  conciergeResponsibleId?: string
}

export interface Process {
  id: string
  name: string
  description: string
}

export interface ProcessStage {
  id: string
  processId: string
  name: string
  order: number
}

export interface TaskHistory {
  id: string
  date: string
  user: string
  action: string
}

export interface TaskComment {
  id: string
  author: string
  date: string
  text: string
}

export type TaskType =
  | 'Operacional'
  | 'Concierge'
  | 'Demanda'
  | 'Manutenção'
  | 'Vistoria'
  | 'Administrativo'

export type TaskPriority = 'Baixa' | 'Média' | 'Alta' | 'Crítica'

export interface Task {
  id: string
  title: string
  stageId: string
  propertyId?: string
  contractId?: string
  assigneeIds: string[]
  type?: TaskType
  deadline: string
  sla: number // hours
  status: 'Pendente' | 'Em Andamento' | 'Concluída' | 'Atrasada'
  priority: TaskPriority
  notes: string
  attachments: { id: string; name: string; url: string }[]
  history?: TaskHistory[]
  delayStatus?: 'on-time' | 'delayed' | 'critical'
  autoGenerated?: boolean
  comments?: TaskComment[]
  specialStatus?: 'Nenhum' | 'Em acompanhamento' | 'Crítica'
  aiUrgency?: 'Normal' | 'Alta' | 'Crítica'
  aiRiskFlag?: boolean
}

export interface TaskChecklistItem {
  id: string
  taskId: string
  description: string
  isCompleted: boolean
  isMandatory?: boolean
}

export interface Maintenance {
  id: string
  propertyId: string
  contractId?: string
  requesterId: string
  description: string
  status: 'Aberto' | 'Em Orçamento' | 'Aprovado' | 'Em Execução' | 'Concluído'
  reportedDate: string
  scheduledDate?: string
  cost?: number
  payer?: 'Inquilino' | 'Proprietário' | 'Ambos' | 'Imobiliária'
  assignedProfessional?: string
}

export interface Inspection {
  id: string
  propertyId: string
  contractId?: string
  inspectorId: string
  type: 'Entrada' | 'Saída' | 'Rotina' | 'Preventiva'
  date: string
  status: 'Agendada' | 'Em Andamento' | 'Concluída' | 'Cancelada'
  reportUrl?: string
  maintenanceRequired?: boolean
  entryPhotoUrl?: string
  exitPhotoUrl?: string
}

export interface ContractEvent {
  id: string
  contractId: string
  date: string
  title: string
  type: 'contract' | 'inspection' | 'maintenance' | 'call' | 'success' | 'system' | 'alert' | 'nps'
  description: string
}

export interface MoveOutFlow {
  id: string
  contractId: string
  noticeDate: string
  expectedExitDate: string
  stage: 'aviso' | 'vistoria' | 'reparos' | 'acerto' | 'chaves' | 'concluido'
}

export interface WorkflowStageTask {
  id: string
  name: string
  sla: number
  isMandatory: boolean
  hasChecklist: boolean
}

export interface WorkflowStageTemplate {
  id: string
  name: string
  tasks: WorkflowStageTask[]
}

export interface WorkflowTemplate {
  id: string
  name: string
  type: string
  version: string
  isActive: boolean
  stages: WorkflowStageTemplate[]
}

export interface NPSResponse {
  id: string
  clientId: string
  contractId?: string
  score: number // 0-10
  classification: 'Promotor' | 'Neutro' | 'Detrator'
  date: string
  comment?: string
  sourceTrigger: string
  googleReviewSent: boolean
}

export type ConciergeStage =
  | 'INICIO'
  | 'D+5'
  | 'FINANCEIRO'
  | 'ESTABILIZACAO'
  | 'OPERACAO'
  | 'MANUTENCAO_6M'
  | 'PRE_RENOVACAO'
  | 'NEGOCIACAO'
  | 'FINALIZADO'
  | 'RISCO'

export interface ConciergeRecord {
  id: string
  cliente_nome: string
  proprietario_nome: string
  imovel: string
  contrato_id: string
  data_entrega_chave: string
  data_inicio_contrato: string
  data_fim_contrato: string
  data_vencimento_boleto: string
  etapa_atual: ConciergeStage
  responsavel_atual: string
  ultimo_contato: string
  proximo_contato: string
  status_cliente: 'ativo' | 'risco' | 'renovacao' | 'encerrado'
}
