import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Clock, Zap, AlertCircle } from 'lucide-react'
import { cn } from '@/lib/utils'

interface KanbanCardProps {
  task: {
    id: string
    title: string
    property: string
    priority: string
    assignees: string[]
    image: string
    deadline?: string
    delayStatus?: 'on-time' | 'delayed' | 'critical'
    autoGenerated?: boolean
  }
}

const priorityColors: Record<string, string> = {
  Baixa: 'bg-emerald-100 text-emerald-700',
  Média: 'bg-blue-100 text-blue-700',
  Alta: 'bg-orange-100 text-orange-700',
  Crítica: 'bg-red-100 text-red-700',
}

const priorityBorders: Record<string, string> = {
  Baixa: 'border-l-emerald-500',
  Média: 'border-l-blue-500',
  Alta: 'border-l-orange-500',
  Crítica: 'border-l-red-500',
}

export function KanbanCard({ task }: KanbanCardProps) {
  const isDelayed = task.delayStatus === 'delayed'
  const isCritical = task.delayStatus === 'critical'

  const checkIsLate = () => {
    if (!task.deadline) return false
    try {
      const parts = task.deadline.split(' ')
      const [day, month, year] = parts[0].split('/')
      const [hour, minute] = (parts[1] || '23:59').split(':')
      const deadlineDate = new Date(
        Number(year),
        Number(month) - 1,
        Number(day),
        Number(hour),
        Number(minute),
      )
      return deadlineDate < new Date()
    } catch (e) {
      return false
    }
  }

  const late = checkIsLate()

  return (
    <Card
      className={cn(
        'cursor-grab hover:shadow-md transition-all group mb-3 relative overflow-hidden border-l-4 border-y border-r bg-card',
        priorityBorders[task.priority] || 'border-l-border',
      )}
    >
      <div className="h-20 w-full overflow-hidden bg-muted relative">
        <img
          src={task.image}
          alt="Imóvel"
          className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-500 opacity-90"
        />
        <div className="absolute top-2 right-2 flex gap-1">
          {task.autoGenerated && (
            <Badge
              variant="secondary"
              className="text-[9px] py-0 h-4 bg-background/90 backdrop-blur-sm shadow-sm"
            >
              <Zap className="w-2.5 h-2.5 text-primary mr-1" /> Auto
            </Badge>
          )}
          <Badge
            className={cn(
              'text-[9px] py-0 h-4 shadow-sm border-transparent font-bold',
              priorityColors[task.priority] || 'bg-secondary',
            )}
          >
            {task.priority}
          </Badge>
        </div>
      </div>
      <CardContent className="p-3">
        <h4 className="font-semibold text-sm leading-tight line-clamp-2 text-foreground">
          {task.title}
        </h4>

        {task.deadline && (
          <div
            className={cn(
              'flex items-center gap-1 mt-1.5 text-[10px] font-bold tracking-wide',
              late ? 'text-destructive' : 'text-muted-foreground',
            )}
          >
            {late ? <AlertCircle className="w-3 h-3" /> : <Clock className="w-3 h-3" />}
            {late ? `Atrasada (${task.deadline})` : task.deadline}
          </div>
        )}

        {(isDelayed || isCritical) && !late && (
          <div
            className={cn(
              'flex items-center gap-1 mt-1 text-[10px] font-bold uppercase tracking-wide',
              isCritical ? 'text-destructive' : 'text-warning',
            )}
          >
            <Clock className="w-3 h-3" />
            {isCritical ? 'SLA Estourado' : 'Atraso Moderado'}
          </div>
        )}

        <p className="text-xs text-muted-foreground mt-1.5 truncate">{task.property}</p>
        <div className="flex items-center justify-between mt-3 pt-2 border-t border-border/60">
          <div className="flex -space-x-2 overflow-hidden">
            {task.assignees.map((avatar, i) => (
              <Avatar key={i} className="inline-block border-2 border-background h-6 w-6">
                <AvatarImage src={avatar} />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
            ))}
          </div>
          <span className="text-[10px] text-muted-foreground font-medium group-hover:text-primary transition-colors">
            Abrir
          </span>
        </div>
      </CardContent>
    </Card>
  )
}
