import { useState, useMemo, useEffect, useRef } from 'react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Calendar } from '@/components/ui/calendar'
import { Check, ChevronsUpDown, CalendarIcon, Paperclip, X } from 'lucide-react'
import { format } from 'date-fns'
import { cn } from '@/lib/utils'
import { db } from '@/lib/mock-data'
import { Task, TaskType, TaskPriority } from '@/types'
import useAuthStore from '@/stores/useAuthStore'

interface NewTaskDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSave: (task: Task) => void
}

export function NewTaskDialog({ open, onOpenChange, onSave }: NewTaskDialogProps) {
  const { user } = useAuthStore()
  const [title, setTitle] = useState('')
  const [propertyId, setPropertyId] = useState('')
  const [type, setType] = useState<TaskType | ''>('')
  const [priority, setPriority] = useState<TaskPriority>('Média')
  const [deadlineDate, setDeadlineDate] = useState<Date | undefined>(new Date())
  const [deadlineTime, setDeadlineTime] = useState('18:00')
  const [notes, setNotes] = useState('')
  const [openCombobox, setOpenCombobox] = useState(false)
  const [photos, setPhotos] = useState<{ id: string; name: string; url: string }[]>([])
  const fileInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (!open) {
      setTitle('')
      setPropertyId('')
      setType('')
      setPriority('Média')
      setDeadlineDate(new Date())
      setDeadlineTime('18:00')
      setNotes('')
      setOpenCombobox(false)
      setPhotos([])
    }
  }, [open])

  const searchableItems = useMemo(
    () =>
      db.properties.map((p) => {
        const owner = db.clients.find((c) => c.id === p.ownerId)
        return {
          id: p.id,
          searchString: `${p.id} ${p.address} ${p.title} ${owner?.name || ''}`.toLowerCase(),
          display: `${p.address} - ${owner?.name || 'Sem proprietário'}`,
          code: p.id,
        }
      }),
    [],
  )

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || [])
    files.forEach((file) => {
      const reader = new FileReader()
      reader.onload = (ev) => {
        if (ev.target?.result) {
          setPhotos((prev) => [
            ...prev,
            {
              id: Date.now().toString() + Math.random(),
              name: file.name,
              url: ev.target.result as string,
            },
          ])
        }
      }
      reader.readAsDataURL(file)
    })
  }

  const handleCreate = () => {
    if (!title || !propertyId || !type) return
    const finalDeadline = deadlineDate
      ? `${format(deadlineDate, 'dd/MM/yyyy')} ${deadlineTime}`
      : new Date().toLocaleDateString('pt-BR')

    const newTask: Task = {
      id: `t_new_${Date.now()}`,
      title,
      propertyId,
      stageId: '',
      assigneeIds: [user.id],
      type: type as TaskType,
      priority,
      deadline: finalDeadline,
      sla: 48,
      status: 'Pendente',
      notes,
      attachments: photos,
      autoGenerated: false,
      delayStatus: 'on-time',
    }
    onSave(newTask)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px] overflow-y-auto max-h-[90vh]">
        <DialogHeader>
          <DialogTitle>Nova Tarefa Operacional</DialogTitle>
          <DialogDescription>Crie uma nova demanda e vincule-a a um imóvel.</DialogDescription>
        </DialogHeader>

        <div className="grid gap-4 py-2">
          <div className="grid gap-2">
            <Label>Título da Tarefa</Label>
            <Input
              placeholder="Ex: Conserto de Infiltração"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </div>

          <div className="grid gap-2">
            <Label>Vincular Imóvel / Cliente</Label>
            <Popover open={openCombobox} onOpenChange={setOpenCombobox}>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  role="combobox"
                  className="justify-between w-full bg-card"
                >
                  <span className="truncate pr-4">
                    {searchableItems.find((i) => i.id === propertyId)?.display || 'Buscar...'}
                  </span>
                  <ChevronsUpDown className="ml-2 h-4 w-4 opacity-50 shrink-0" />
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0" align="start">
                <Command>
                  <CommandInput placeholder="Digite para buscar..." />
                  <CommandList>
                    <CommandEmpty>Nenhum resultado.</CommandEmpty>
                    <CommandGroup>
                      {searchableItems.map((item) => (
                        <CommandItem
                          key={item.id}
                          value={item.searchString}
                          onSelect={() => {
                            setPropertyId(item.id)
                            setOpenCombobox(false)
                          }}
                        >
                          <Check
                            className={cn(
                              'mr-2 h-4 w-4 shrink-0',
                              propertyId === item.id ? 'opacity-100' : 'opacity-0',
                            )}
                          />
                          <div className="flex flex-col truncate">
                            <span className="truncate">{item.display}</span>
                            <span className="text-xs text-muted-foreground">Cód: {item.code}</span>
                          </div>
                        </CommandItem>
                      ))}
                    </CommandGroup>
                  </CommandList>
                </Command>
              </PopoverContent>
            </Popover>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label>Tipo de Tarefa</Label>
              <Select value={type} onValueChange={(val: any) => setType(val)}>
                <SelectTrigger className="bg-card">
                  <SelectValue placeholder="Categoria" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Manutenção">Manutenção</SelectItem>
                  <SelectItem value="Vistoria">Vistoria</SelectItem>
                  <SelectItem value="Operacional">Operacional</SelectItem>
                  <SelectItem value="Concierge">Concierge</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label>Prioridade</Label>
              <Select value={priority} onValueChange={(val: any) => setPriority(val)}>
                <SelectTrigger className="bg-card">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Baixa">Baixa</SelectItem>
                  <SelectItem value="Média">Média</SelectItem>
                  <SelectItem value="Alta">Alta</SelectItem>
                  <SelectItem value="Crítica">Crítica</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label>Data Limite</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    className={cn(
                      'w-full justify-start text-left font-normal bg-card',
                      !deadlineDate && 'text-muted-foreground',
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {deadlineDate ? (
                      format(deadlineDate, 'dd/MM/yyyy')
                    ) : (
                      <span>Selecione a data</span>
                    )}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={deadlineDate}
                    onSelect={setDeadlineDate}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>
            <div className="grid gap-2">
              <Label>Hora Limite</Label>
              <Input
                type="time"
                value={deadlineTime}
                onChange={(e) => setDeadlineTime(e.target.value)}
                className="bg-card"
              />
            </div>
          </div>

          <div className="grid gap-2">
            <Label>Anexo de Fotos</Label>
            <input
              type="file"
              hidden
              ref={fileInputRef}
              multiple
              accept="image/*"
              onChange={handleFileChange}
            />
            <Button
              type="button"
              variant="outline"
              onClick={() => fileInputRef.current?.click()}
              className="w-full border-dashed bg-muted/30"
            >
              <Paperclip className="w-4 h-4 mr-2" /> Fazer Upload de Imagens
            </Button>
            {photos.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-2">
                {photos.map((p) => (
                  <div
                    key={p.id}
                    className="relative group w-16 h-16 rounded-md overflow-hidden border border-border"
                  >
                    <img src={p.url} alt={p.name} className="w-full h-full object-cover" />
                    <button
                      type="button"
                      onClick={() => setPhotos((prev) => prev.filter((x) => x.id !== p.id))}
                      className="absolute top-0 right-0 bg-black/60 text-white p-0.5 rounded-bl-md opacity-0 group-hover:opacity-100 transition-opacity"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="grid gap-2">
            <Label>Observações</Label>
            <Textarea
              placeholder="Detalhes da solicitação..."
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="min-h-[80px] bg-card"
            />
          </div>
        </div>

        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Cancelar
          </Button>
          <Button onClick={handleCreate} disabled={!title || !propertyId || !type}>
            Criar Tarefa
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
