import { useState } from 'react'
import { PermissionGate } from '@/components/shared/PermissionGate'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Plus, Search, CheckSquare, Clock, AlertTriangle } from 'lucide-react'
import useDataStore from '@/stores/useDataStore'
import { Task } from '@/types'

export default function Tarefas() {
  const { db } = useDataStore()
  const [searchTerm, setSearchTerm] = useState('')

  const filteredTasks = db.tasks.filter((t) =>
    t.title.toLowerCase().includes(searchTerm.toLowerCase()),
  )

  const pendingCount = db.tasks.filter((t) => t.status !== 'Concluída').length
  const delayedCount = db.tasks.filter((t) => t.status === 'Atrasada').length

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'Crítica':
        return 'text-destructive bg-destructive/10'
      case 'Alta':
        return 'text-orange-600 bg-orange-50'
      case 'Média':
        return 'text-blue-600 bg-blue-50'
      default:
        return 'text-slate-600 bg-slate-50'
    }
  }

  return (
    <div className="p-6 max-w-7xl mx-auto animate-fade-in-up space-y-8 pb-10">
      {/* Header & Controls */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-2">
            <CheckSquare className="w-8 h-8 text-primary" /> Tarefas e O.S.
          </h1>
          <p className="text-muted-foreground mt-1 text-lg">
            Acompanhe as demandas operacionais, SLAs e histórico de execuções.
          </p>
        </div>

        <div className="flex gap-3 w-full sm:w-auto">
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Buscar tarefa..."
              className="pl-9 bg-card"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          {/* SECURE GATE: Only users with 'create' permission on 'tasks' module can see this button */}
          <PermissionGate module="tasks" action="create">
            <Button className="shadow-sm">
              <Plus className="w-4 h-4 mr-2" />
              Nova Tarefa
            </Button>
          </PermissionGate>
        </div>
      </div>

      {/* Overview Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="p-4 rounded-xl border bg-card shadow-sm flex items-center gap-4">
          <div className="p-3 bg-primary/10 text-primary rounded-lg">
            <CheckSquare className="w-6 h-6" />
          </div>
          <div>
            <p className="text-sm font-medium text-muted-foreground">Total de Tarefas</p>
            <p className="text-2xl font-bold">{db.tasks.length}</p>
          </div>
        </div>
        <div className="p-4 rounded-xl border bg-card shadow-sm flex items-center gap-4">
          <div className="p-3 bg-blue-500/10 text-blue-500 rounded-lg">
            <Clock className="w-6 h-6" />
          </div>
          <div>
            <p className="text-sm font-medium text-muted-foreground">Em Andamento / Pendentes</p>
            <p className="text-2xl font-bold">{pendingCount}</p>
          </div>
        </div>
        <div className="p-4 rounded-xl border bg-card shadow-sm flex items-center gap-4">
          <div className="p-3 bg-destructive/10 text-destructive rounded-lg">
            <AlertTriangle className="w-6 h-6" />
          </div>
          <div>
            <p className="text-sm font-medium text-muted-foreground">Tarefas Atrasadas</p>
            <p className="text-2xl font-bold text-destructive">{delayedCount}</p>
          </div>
        </div>
      </div>

      {/* Task List */}
      <div className="grid gap-3">
        {filteredTasks.length > 0 ? (
          filteredTasks.map((t) => (
            <div
              key={t.id}
              className="p-5 border rounded-xl bg-card shadow-sm hover:shadow-md transition-shadow flex flex-col sm:flex-row gap-4 sm:items-center justify-between group"
            >
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <h3 className="font-semibold text-lg">{t.title}</h3>
                  {t.autoGenerated && (
                    <Badge variant="outline" className="text-[10px] uppercase bg-muted/50">
                      Automática
                    </Badge>
                  )}
                </div>
                <div className="text-sm text-muted-foreground flex flex-wrap gap-x-4 gap-y-2 mt-2">
                  <span className="flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" /> Prazo: {t.deadline} (SLA: {t.sla}h)
                  </span>
                  <span>Tipo: {t.type || 'Geral'}</span>
                  {t.contractId && <span>Contrato: {t.contractId}</span>}
                </div>
              </div>

              <div className="flex items-center gap-3 sm:gap-6 justify-between sm:justify-end border-t sm:border-t-0 pt-3 sm:pt-0">
                <div
                  className={`px-2.5 py-1 text-xs font-semibold rounded-full ${getPriorityColor(t.priority)}`}
                >
                  {t.priority}
                </div>
                <Badge
                  variant={
                    t.status === 'Concluída'
                      ? 'success'
                      : t.status === 'Atrasada'
                        ? 'destructive'
                        : 'secondary'
                  }
                >
                  {t.status}
                </Badge>

                {/* SECURE GATE: Only users with 'edit' permission can update existing records */}
                <PermissionGate module="tasks" action="edit">
                  <Button
                    variant="outline"
                    size="sm"
                    className="opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    Editar
                  </Button>
                </PermissionGate>
              </div>
            </div>
          ))
        ) : (
          <div className="p-12 text-center border-2 border-dashed rounded-xl text-muted-foreground bg-muted/10">
            Nenhuma tarefa encontrada com os filtros atuais.
          </div>
        )}
      </div>
    </div>
  )
}
